# Generated by Django 5.1.7 on 2025-05-06 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_child',
        ),
        migrations.AddField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PARENT'}, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Родители (для Студента)'),
        ),
    ]
