# Generated by Django 5.1.7 on 2025-05-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок действия токена подтверждения email'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='токен сброса пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='срок действия токена сброса пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='токен подтверждения email'),
        ),
    ]
