# Generated by Django 5.1.7 on 2025-05-28 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='токен подтверждения email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='токен сброса пароля'),
        ),
    ]
