# Generated by Django 5.1.7 on 2025-05-17 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0003_alter_studentgroup_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date_given',
            field=models.DateField(default=datetime.date.today, verbose_name='дата выставления'),
        ),
    ]
