# Generated by Django 5.1.7 on 2025-05-19 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0004_alter_grade_date_given'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annual_grades_in_core', to='edu_core.academicyear', verbose_name='учебный год (для годовых итоговых)'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='study_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades_in_period', to='edu_core.studyperiod', verbose_name='учебный период (для текущих и итоговых за период)'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject', 'academic_year', 'date_given'], name='edu_core_gr_student_57fb74_idx'),
        ),
    ]
