# Generated by Django 5.1.7 on 2025-05-19 10:24

import django.db.models.deletion
import edu_core.models
import edu_core.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0006_alter_homeworkattachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='file',
        ),
        migrations.AlterField(
            model_name='homeworkattachment',
            name='file',
            field=models.FileField(upload_to=edu_core.models.homework_attachment_upload_path, verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='submissionattachment',
            name='file',
            field=models.FileField(upload_to=edu_core.models.submission_attachment_upload_path, verbose_name='файл'),
        ),
        migrations.CreateModel(
            name='SubjectMaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=edu_core.storages.OverwriteKeepOriginalNameStorage(), upload_to=edu_core.models.material_attachment_upload_path, verbose_name='файл')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='edu_core.subjectmaterial', verbose_name='учебный материал')),
            ],
            options={
                'verbose_name': 'прикрепленный файл к учебному материалу',
                'verbose_name_plural': 'прикрепленные файлы к учебным материалам',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
