# Generated by Django 5.1.7 on 2025-05-31 08:24

import edu_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_core', '0007_remove_subjectmaterial_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterialattachment',
            name='file',
            field=models.FileField(upload_to=edu_core.models.material_attachment_upload_path, verbose_name='файл'),
        ),
    ]
