# Generated by Django 5.1.7 on 2025-03-26 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True, verbose_name='номер/название')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='вместимость')),
                ('type', models.CharField(choices=[('LECTURE', 'Лекционная'), ('PRACTICE', 'Практическая'), ('LAB', 'Лаборатория'), ('COMPUTER', 'Компьютерный класс'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='тип аудитории')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'аудитория',
                'verbose_name_plural': 'аудитории',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название предмета')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название группы')),
                ('curator', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='куратор')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='студенты')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('LECTURE', 'Лекция'), ('PRACTICE', 'Практика'), ('SEMINAR', 'Семинар'), ('LAB', 'Лабораторная работа'), ('EXAM', 'Экзамен/Зачет'), ('CONSULTATION', 'Консультация'), ('OTHER', 'Другое')], default='LECTURE', max_length=20, verbose_name='тип занятия')),
                ('start_time', models.DateTimeField(verbose_name='время начала')),
                ('end_time', models.DateTimeField(verbose_name='время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='schedule.classroom', verbose_name='аудитория')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['TEACHER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='кем создано')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_taught', to=settings.AUTH_USER_MODEL, verbose_name='преподаватель')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.studentgroup', verbose_name='группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
                'ordering': ['start_time', 'group'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='schedule_le_start_t_c7a80b_idx'), models.Index(fields=['teacher', 'start_time'], name='schedule_le_teacher_1b6951_idx'), models.Index(fields=['group', 'start_time'], name='schedule_le_group_i_6afb3b_idx'), models.Index(fields=['classroom', 'start_time'], name='schedule_le_classro_5add46_idx')],
            },
        ),
    ]
