# Generated by Django 5.1.7 on 2025-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('LECTURE', 'Лекционная'), ('PRACTICE', 'Практическая'), ('LAB', 'Лабораторная работа'), ('SEMINAR', 'Семинар'), ('COMPUTER', 'Компьютерный класс'), ('PHYSICAL_EDUCATION', 'Физкультура'), ('GYM', 'Спортзал'), ('ART', 'ИЗО / Художественный класс'), ('MUSIC', 'Музыка'), ('HOMEROOM', 'Классный час'), ('EXAM', 'Экзамен'), ('TEST', 'Контрольная / Тест'), ('PROJECT', 'Проектная работа'), ('CONSULTATION', 'Консультация'), ('ELECTIVE', 'Факультатив / Электив'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='тип аудитории'),
        ),
    ]
