# Generated by Django 5.1.7 on 2025-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_classroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('LECTURE', 'Лекционная'), ('PRACTICE', 'Практическая'), ('LAB', 'Лаборатория'), ('COMPUTER', 'Компьютерный класс'), ('SCIENCE', 'Кабинет химии/физики/биологии'), ('LANGUAGE', 'Кабинет иностранных языков'), ('MUSIC', 'Кабинет музыки'), ('ART', 'Кабинет ИЗО/творчества'), ('GYM', 'Спортзал'), ('AUDITORIUM', 'Актовый зал'), ('ADMIN', 'Административный кабинет'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='тип аудитории'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('LECTURE', 'Лекция'), ('PRACTICE', 'Практика'), ('SEMINAR', 'Семинар'), ('LAB', 'Лабораторная работа'), ('EXAM', 'Экзамен/Зачет'), ('CONSULTATION', 'Консультация'), ('CLASS', 'Урок'), ('HOMEROOM', 'Классный час'), ('EXTRA', 'Факультатив / Внеурочное занятие'), ('SPORT', 'Физкультура'), ('ART', 'ИЗО / Музыка / Творчество'), ('OTHER', 'Другое')], default='LECTURE', max_length=20, verbose_name='тип занятия'),
        ),
    ]
