# Generated by Django 5.1.7 on 2025-05-10 10:01

import django.db.models.deletion
import messaging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('PRIVATE', 'Личный чат'), ('GROUP', 'Групповой чат')], max_length=10, verbose_name='тип чата')),
                ('name', models.CharField(blank=True, help_text='Обязательно для групповых чатов', max_length=150, null=True, verbose_name='название чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ['-last_message__timestamp', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='присоединился')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chat', verbose_name='чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'участник чата',
                'verbose_name_plural': 'участники чатов',
                'ordering': ['chat', 'joined_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='chats', through='messaging.ChatParticipant', to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to=messaging.models.chat_file_upload_path, verbose_name='файл')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='время отправки')),
                ('mime_type', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='MIME тип')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер файла')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='исходное имя файла')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chat', verbose_name='чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='messaging_m_chat_id_71a86f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'mime_type'], name='messaging_m_chat_id_fc2e63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('user', 'chat')},
        ),
    ]
