# Generated by Django 5.1.7 on 2025-05-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, help_text='Обязательно для групповых чатов', max_length=150, null=True, verbose_name='название чата'),
        ),
    ]
