# Generated by Django 5.1.7 on 2025-05-23 15:16

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=messaging.models.chat_file_upload_path, verbose_name='файл'),
        ),
    ]
