# Generated by Django 5.1.7 on 2025-05-03 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_chat_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='размер файла'),
        ),
        migrations.AddField(
            model_name='message',
            name='mime_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='MIME тип'),
        ),
        migrations.AddField(
            model_name='message',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='исходное имя файла'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'mime_type'], name='messaging_m_chat_id_fc2e63_idx'),
        ),
    ]
