# Generated by Django 5.1.7 on 2025-05-10 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_news', models.BooleanField(default=True, verbose_name='новости')),
                ('enable_schedule', models.BooleanField(default=True, verbose_name='расписание')),
                ('enable_messages', models.BooleanField(default=True, verbose_name='сообщения')),
                ('enable_forum', models.BooleanField(default=True, verbose_name='форум')),
                ('enable_system', models.BooleanField(default=True, verbose_name='системные')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'настройки уведомлений',
                'verbose_name_plural': 'настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='текст уведомления')),
                ('notification_type', models.CharField(choices=[('NEWS', 'Новость'), ('SCHEDULE', 'Расписание'), ('MESSAGE', 'Сообщение'), ('FORUM', 'Форум'), ('SYSTEM', 'Системное')], default='SYSTEM', max_length=20, verbose_name='тип уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='прочитано')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
