# Generated by Django 5.1.7 on 2025-05-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_quiz',
            field=models.BooleanField(default=True, verbose_name='тесты/результаты'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEWS', 'Новость'), ('SCHEDULE', 'Расписание'), ('MESSAGE', 'Сообщение'), ('FORUM', 'Форум'), ('QUIZ', 'Тест/Результат теста'), ('SYSTEM', 'Системное')], default='SYSTEM', max_length=20, verbose_name='тип уведомления'),
        ),
    ]
