# Generated by Django 5.1.7 on 2025-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotificationsettings_enable_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='enable_forum',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='enable_news',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='enable_quiz',
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_assignment_due',
            field=models.BooleanField(default=True, verbose_name='напоминания о сроках ДЗ'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_assignment_graded',
            field=models.BooleanField(default=True, verbose_name='проверка/оценка ДЗ'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_assignment_new',
            field=models.BooleanField(default=True, verbose_name='новые ДЗ'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_assignment_submitted',
            field=models.BooleanField(default=True, verbose_name='сдача ДЗ (для преподавателя)'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_grade_new',
            field=models.BooleanField(default=True, verbose_name='новые оценки'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_quiz_due',
            field=models.BooleanField(default=True, verbose_name='напоминания о сроках тестов'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_quiz_new',
            field=models.BooleanField(default=True, verbose_name='новые тесты'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='enable_quiz_result',
            field=models.BooleanField(default=True, verbose_name='результаты тестов'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SCHEDULE', 'Расписание'), ('MESSAGE', 'Сообщение в чате'), ('ASSIGNMENT_NEW', 'Новое домашнее задание'), ('ASSIGNMENT_DUE', 'Срок сдачи ДЗ'), ('ASSIGNMENT_SUBMITTED', 'ДЗ сдано'), ('ASSIGNMENT_GRADED', 'ДЗ проверено/оценено'), ('GRADE_NEW', 'Новая оценка'), ('QUIZ_NEW', 'Новый тест назначен'), ('QUIZ_RESULT', 'Результат теста'), ('QUIZ_DUE', 'Срок сдачи теста'), ('SYSTEM', 'Системное')], default='SYSTEM', max_length=25, verbose_name='тип уведомления'),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='enable_messages',
            field=models.BooleanField(default=True, verbose_name='сообщения в чате'),
        ),
    ]
