# Generated by Django 5.1.7 on 2025-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_usernotificationsettings_enable_forum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='enable_quiz_due',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='enable_quiz_new',
        ),
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='enable_quiz_result',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SCHEDULE', 'Расписание'), ('MESSAGE', 'Сообщение в чате'), ('ASSIGNMENT_NEW', 'Новое домашнее задание'), ('ASSIGNMENT_DUE', 'Срок сдачи ДЗ'), ('ASSIGNMENT_SUBMITTED', 'ДЗ сдано'), ('ASSIGNMENT_GRADED', 'ДЗ проверено/оценено'), ('GRADE_NEW', 'Новая оценка'), ('SYSTEM', 'Системное')], default='SYSTEM', max_length=25, verbose_name='тип уведомления'),
        ),
    ]
